### ISSUE TITLE
check on XOMO

### ISSUE THREAD

**Issue by ginfung** [ai-se/surrogate#9]

**Comment by vivekaxl** [comment]
[Surrogate_Study.xlsx](https://github.com/ai-se/surrogate/files/106912/Surrogate_Study.xlsx)

Yellow: Best in the column
Red: Our recommended method

surrogate_generate: Decision Tree
surrogate_generate_LR: Linear Regression
poles_point: WHERE down to the leaves and use the poles (2/cluster)
random_point: WHERE down to the leaves and use any point (1/cluster)
median_point: WHERE down to the leaves and use the median point(not based on the projection distance(1/cluster)
